WebReportMWM v40.0.0/WebReportMWM/Controllers/CrudOperadoresController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebReportMWM.Models;
using WebReportMWM.Models.Entitys;
using WebReportMWM.services;

namespace WebReportMWM.Controllers
{
    [Authorize(Roles = "S")]
    public class CrudOperadoresController : Controller
    {
        // GET: CrudOperadores
        public ActionResult Create()
        {
            using (var context = new DMMeatWeigherModel())
            {
                Operadores model = new Operadores();
                ViewBag.ModeCreate = true;
                return View("UpdateCreate", model);
            }
        }

        [HttpPost]
        public ActionResult Create(Operadores model)
        {
            using(var context = new DMMeatWeigherModel())
            {
                Operadores newOperador = new Operadores();
                newOperador.Nombre = model.Nombre;
                newOperador.pasw = model.pasw;
                newOperador.Tipo = model.Tipo;

                ResultValidate resultValidation = DbServices.ValidateCreate_Operador(newOperador);
                if(resultValidation.Validated)
                {
                    context.operadores.Add(newOperador);
                    context.SaveChanges();
                    return RedirectToAction("List", new { idRowSelect = newOperador.Id });
                } else
                {
                    TempData["MessagesError"] = resultValidation.ErrorMessages;
                    ViewBag.ModeCreate = true;
                    return View("UpdateCreate", newOperador);
                }
            }
        }

        [HttpGet]
        public ActionResult List(int? idRowSelect)
        {
            if (idRowSelect == null)
                idRowSelect = 0;
            using (var context = new DMMeatWeigherModel())
            {
                var data = (from o in context.operadores select new
                {
                        Id = o.Id,
                        Nombre = o.Nombre,
                        Password = o.pasw,
                        Tipo = o.Tipo == "S" ? "SUPERVISOR" : "USUARIO"
                    }).AsEnumerable().Select(x => new Operadores()
                    {
                        Id = x.Id,
                        Nombre = x.Nombre,
                        pasw = x.Password,
                        Tipo = x.Tipo
                    }).ToList();
                ViewBag.IdRowSelect = idRowSelect;
                return View(data);
            }
        }

        public ActionResult Update(int idOperador)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var date = context.operadores.Where(x => x.Id == idOperador).SingleOrDefault();
                Operadores model = new Operadores()
                {
                    Id = date.Id,
                    Nombre = date.Nombre,
                    pasw = date.pasw,
                    Tipo = date.Tipo,
                };
                ViewBag.ModeCreate = false;
                return View("UpdateCreate", model);
            }
        }

        [HttpPost]
        public ActionResult Update(Operadores model)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var data = context.operadores.FirstOrDefault(x => x.Id == model.Id);
                if(data != null)
                {
                    data.Nombre = model.Nombre;
                    data.pasw = model.pasw;
                    data.Tipo = model.Tipo;
                }

                ResultValidate resultValidation = DbServices.ValidateUpdate_Operador(data.Id, data.Nombre);
                if (resultValidation.Validated)
                {
                    context.SaveChanges();
                    return RedirectToAction("List", new { idRowSelect = data.Id });
                } else
                {
                    TempData["MessagesError"] = resultValidation.ErrorMessages;
                    ViewBag.ModeCreate = false;
                    return View("UpdateCreate", data);
                }
            }
        }

        public ActionResult ConfirmDelete(int idOperador)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var data = context.operadores.FirstOrDefault(x => x.Id == idOperador);
                return View(data);
            }
        }

        [HttpPost]
        public ActionResult Delete(int idOperador)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var data = context.operadores.FirstOrDefault(x => x.Id == idOperador);
                if(data != null)
                {
                    var resultValidation = DbServices.ValidateDelete_Operador(data.Id);
                    if (resultValidation.Validated)
                    {
                        context.operadores.Remove(data);
                        context.SaveChanges();
                        return RedirectToAction("List");
                    } else
                    {
                        TempData["MessagesError"] = resultValidation.ErrorMessages;
                        return View("ConfirmDelete", data);
                    }
                } else
                {
                    ViewBag.Message = "En base de datos: No se ha podido eliminar el Operador.";
                    return View("Error");
                }
            }
        }
    }
}

WebReportMWM v40.0.0/WebReportMWM/Views/CrudOperadores/ConfirmDelete.cshtml
@model WebReportMWM.Models.Entitys.Operadores
@{
    ViewBag.Title = "Delete";
}

<h2>Borrar</h2>
<hr />
<h3>Confirma Eliminar este Operador?</h3>

@using (Html.BeginForm("Delete", "CrudOperadores", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <input type="hidden" id="idOperador" name="idOperador" value="@Model.Id" />

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Borrar" class="btn btn-danger" />
                @Html.ActionLink("Listar", "List", "CrudOperadores", new { @class = "btn btn-info" })
            </div>
        </div>
    </div>

    if (TempData["MessagesError"] != null && ((List<string>)TempData["MessagesError"]).Count > 0)
    {
        foreach (string msg in (List<string>)TempData["MessagesError"])
        {
            <p style="color:red;">@msg</p>
        }
    }
}

WebReportMWM v40.0.0/WebReportMWM/Views/CrudOperadores/List.cshtml
@model IEnumerable<WebReportMWM.Models.Entitys.Operadores>
@{
    ViewBag.Title = "List";
}

@{ WebGrid webGrid = new WebGrid(source: Model, canPage: false, canSort: false);

    string IdRowSelect = ViewBag.IdRowSelect == null ? "0" : ((int)ViewBag.IdRowSelect).ToString();
  
}


<h2>Lista de Operadores</h2>

<p>
    <a href="~/CrudOperadores/Create" class="btn btn-default btn-sm">
        <i class="glyphicon glyphicon-star" style="color: aqua;"></i>
        <span>
            <strong>Crear Nuevo</strong>
        </span>
    </a>
</p>

@webGrid.GetHtml(htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
            tableStyle: "table table-bordered",
            rowStyle: "webgrid-row",
            fillEmptyRows: false,
            alternatingRowStyle: "alt",
            headerStyle: "webgrid-header",
            columns: webGrid.Columns(
            webGrid.Column(columnName: "Id", header: "Id", style: "Id"),
            webGrid.Column(columnName: "Nombre", header: "Nombre", style: "colnombre"),
webGrid.Column(columnName: "Tipo", header: "Tipo", style: "coltipo"), 
webGrid.Column(header: "", style: "collinks", format:@<span class="link">
            @Html.ActionLink(" ", "Update", new { idOperador = item.Id }, new { @class = "glyphicon glyphicon-edit", title = "Editar" }) |
            @Html.ActionLink(" ", "ConfirmDelete", new { idOperador = item.Id }, new { @style = "color:#ff0000;", @class = "glyphicon glyphicon-trash", title = "Eliminar" })
        </span>)))

   
    <style type="text/css">
        .webgrid-header th {
            padding: 6px 5px;
            text-align: center;
            background-color: #e8eef4;
            border-bottom: 2px solid #3966A2;
            height: 40px;
            font-weight: bold;
            border-top: 2px solid #D6E8FF;
            border-left: 2px solid #D6E8FF;
            border-right: 2px solid #D6E8FF;
        }

        .alt {
            background-color: #FBFBFB;
            color: #000;
        }

        .label {
            color: #000;
            font-weight: normal;
        }

        .selectedrow {
            background-color: gold;
        }

        .collinks {
            width: 8%;
            text-align: center;
        }

        .coltipo {
            width: 15%;
            text-align: center;
        }

        .colnombre {
            justify-content: left;
        }
    </style>

<script type="text/javascript" src="~/Scripts/jquery-3.4.1.min.js"></script>

<script type="text/javascript">
    //Al iniciar la carga del documento selecciono el registro especificado por su valor de Id
    //Tambien pongo al registro visible controlando el scroll.
    $(document).ready(function () {
        $('#WebGrid tr').each(function () {
            var Id = $(this).find(".Id").html();
            if (Id == @IdRowSelect)
            {
                $(this).click();
                $(document).scrollTop($(this).position().top);
            }
        });

        $("#WebGrid th:nth-child(1),td:nth-child(1)").hide();

    });

    $("body").on("click", "#WebGrid tr", function () {
        $("#WebGrid").find("td").removeClass("selectedrow");
        $(this).find("td").addClass("selectedrow");
    });
</script>

WebReportMWM v40.0.0/WebReportMWM/Views/CrudOperadores/UpdateCreate.cshtml
@model WebReportMWM.Models.Entitys.Operadores
@{
    ViewBag.Title = "create";

    var selectListTiposOperador = new List<SelectListItem>();
    selectListTiposOperador.Add(new SelectListItem { Text = "USUARIO", Value = "U" });
    selectListTiposOperador.Add(new SelectListItem { Text = "SUPERVISOR", Value = "S" });

    bool modeCreate = (bool)ViewBag.ModeCreate;
    string textAction = modeCreate ? "Crear" : "Actualizar";
}

<h2>@textAction</h2>

@using (Html.BeginForm(modeCreate ? "Create" : "Update", "CrudOperadores", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Operador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pasw, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pasw, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.pasw, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Tipo, selectListTiposOperador, new { htmlAttributes = new { @class = "form-control", id = "iddropdownlistTiposOperador" } })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@textAction class="btn btn-danger" />
                @Html.ActionLink("Listar", "List", "CrudOperadores", new { @class = "btn btn-info" })
                @ViewBag.Message
            </div>
        </div>
    </div>
    if (TempData["MessagesError"] != null && ((List<string>)TempData["MessagesError"]).Count > 0)
    {
        foreach (string msg in (List<string>)TempData["MessagesError"])
        {
            <p style="color:red;">@msg</p>
        }
    }
}

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        /*Esta funcion captura el evento de cambio del dropdownlist para asignar el nuevo id
                 seleccionado al idTipo del modelo. Esto se debe hacer por jquery porque si no el
                 modelo no se actualiza cuando se realiza una seleccion del dropdownlist*/
        $(document).ready(function () {
            $('#iddropdownlist').change(function () {
                $('#idTipo').val($('#iddropdownlist option:selected').val());
            });
        });
    </script>

}