WebReportMWM v40.0.0/WebReportMWM/Controllers/CrudDestinosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebReportMWM.Models;
using WebReportMWM.Models.Entitys;
using WebReportMWM.services;

namespace WebReportMWM.Controllers
{
    [Authorize(Roles = "S")]
    public class CrudDestinosController : Controller
    {
        // GET: CrudDestinos
        public ActionResult Create()
        {
            using (var context = new DMMeatWeigherModel())
            {
                Destino model = new Destino();
                ViewBag.ModeCreate = true;
                return View("UpdateCreate", model);
            }
        }

        [HttpPost]
        public ActionResult Create(Destino model)
        {
            using (var context = new DMMeatWeigherModel())
            {
                Destino newDestino = new Destino();
                newDestino.Nombre = model.Nombre;

                ResultValidate resultValidation = DbServices.ValidateCreate_Destino(newDestino);
                if (resultValidation.Validated)
                {
                    context.Destinos.Add(newDestino);
                    context.SaveChanges();
                    return RedirectToAction("List", new { idRowSelect = newDestino.Id });
                }
                else
                {
                    TempData["MessagesError"] = resultValidation.ErrorMessages;
                    ViewBag.ModeCreate = true;
                    return View("UpdateCreate", newDestino);
                }
            }
        }


        [HttpGet]
        public ActionResult List(int? idRowSelect)
        {
            if (idRowSelect == null)
                idRowSelect = 0;
            using (var context = new DMMeatWeigherModel())
            {
                var data = (from d in context.Destinos
                            select new
                            {
                                Id = d.Id,
                                Nombre = d.Nombre,
                            }).AsEnumerable().Select(x => new Destino()
                            {
                                Id = x.Id,
                                Nombre = x.Nombre,
                            }).ToList();
                ViewBag.IdRowSelect = idRowSelect;
                return View(data);
            }
        }

        public ActionResult Update(int idDestino)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var date = context.Destinos.Where(x => x.Id == idDestino).SingleOrDefault();
                Destino model = new Destino()
                {
                    Id = date.Id,
                    Nombre = date.Nombre,
                };
                ViewBag.ModeCreate = false;
                return View("UpdateCreate", model);
            }
        }

        [HttpPost]
        public ActionResult Update(Destino model)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var data = context.Destinos.FirstOrDefault(x => x.Id == model.Id);
                if (data != null)
                {
                    data.Nombre = model.Nombre;
                }

                ResultValidate resultValidation = DbServices.ValidateUpdate_Destino(data);
                if (resultValidation.Validated)
                {
                    context.SaveChanges();
                    return RedirectToAction("List", new { idRowSelect = data.Id });
                }
                else
                {
                    TempData["MessagesError"] = resultValidation.ErrorMessages;
                    ViewBag.ModeCreate = false;
                    return View("UpdateCreate", data);
                }
            }
        }

        public ActionResult ConfirmDelete(int idDestino)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var data = context.Destinos.FirstOrDefault(x => x.Id == idDestino);
                return View(data);
            }
        }

        [HttpPost]
        public ActionResult Delete(int idDestino)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var data = context.Destinos.FirstOrDefault(x => x.Id == idDestino);
                if (data != null)
                {
                    var resultValidation = DbServices.ValidateDelete_Destino(data.Id);
                    if (resultValidation.Validated)
                    {
                        context.Destinos.Remove(data);
                        context.SaveChanges();
                        return RedirectToAction("List");
                    }
                    else
                    {
                        TempData["MessagesError"] = resultValidation.ErrorMessages;
                        return View("ConfirmDelete", data);
                    }
                }
                else
                {
                    ViewBag.Message = "";
                    return View("Error");
                }
            }
        }
    }
}

WebReportMWM v40.0.0/WebReportMWM/Views/CrudDestinos/ConfirmDelete.cshtml
@model WebReportMWM.Models.Entitys.Destino
@{
    ViewBag.Title = "Delete";
}

<h2>Borrar</h2>

<hr />
<h3>Confirma Eliminar este Destino?</h3>

@using (Html.BeginForm("Delete", "CrudDestinos", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <input type="hidden" id="idDestino" name="idDestino" value="@Model.Id" />

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", disabled = "disabled", @readonly = "readonly" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Borrar" class="btn btn-danger" />
                @Html.ActionLink("Listar", "List", "CrudDestinos", new { @class = "btn btn-info" })
            </div>
        </div>
    </div>

    if (TempData["MessagesError"] != null && ((List<string>)TempData["MessagesError"]).Count > 0)
    {
        foreach (string msg in (List<string>)TempData["MessagesError"])
        {
            <p style="color:red;">@msg</p>
        }
    }
}

WebReportMWM v40.0.0/WebReportMWM/Views/CrudDestinos/List.cshtml
@model IEnumerable<WebReportMWM.Models.Entitys.Destino>
@{
    ViewBag.Title = "List";
}

@{ WebGrid webGrid = new WebGrid(source: Model, canPage: false, canSort: false);

    string IdRowSelect = ViewBag.IdRowSelect == null ? "0" : ((int)ViewBag.IdRowSelect).ToString();

}

<h2>Lista de Destinos</h2>

<p>
    <a href="~/CrudDestinos/Create" class="btn btn-default btn-sm">
        <i class="glyphicon glyphicon-star" style="color: aqua;"></i>
        <span>
            <strong>Crear Nuevo</strong>
        </span>
    </a>
</p>

@webGrid.GetHtml(htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
        tableStyle: "table table-bordered",
        fillEmptyRows: false,
        alternatingRowStyle: "alt",
        headerStyle: "webgrid-header",
        columns: webGrid.Columns(
        webGrid.Column(columnName: "Id", header: "Id", style: "Id"),
        webGrid.Column(columnName: "Nombre", header: "Nombre"),
        webGrid.Column(header: "", style: "collinks", format:@<span class="link">
            @Html.ActionLink(" ", "Update", new { idDestino = item.Id }, new { @class = "glyphicon glyphicon-edit", title = "Editar" }) |
            @Html.ActionLink(" ", "ConfirmDelete", new { idDestino = item.Id }, new { @style = "color:#ff0000;", @class = "glyphicon glyphicon-trash", title = "Eliminar" })
        </span>)))


<style type="text/css">
    .webgrid-header th {
        padding: 6px 5px;
        text-align: center;
        background-color: #e8eef4;
        border-bottom: 2px solid #3966A2;
        height: 40px;
        font-weight: bold;
        border-top: 2px solid #D6E8FF;
        border-left: 2px solid #D6E8FF;
        border-right: 2px solid #D6E8FF;
    }

    .alt {
        background-color: #FBFBFB;
        color: #000;
    }

    .label {
        color: #000;
        font-weight: normal;
    }

    .selectedrow {
        background-color: gold;
    }

    .collinks {
        width: 8%;
        text-align: center;
    }
</style>

<script type="text/javascript" src="~/Scripts/jquery-3.4.1.min.js"></script>

<script type="text/javascript">
    //Al iniciar la carga del documento selecciono el registro especificado por su valor de Id
    //Tambien pongo al registro visible controlando el scroll.
    $(document).ready(function () {
        $('#WebGrid tr').each(function () {
            var Id = $(this).find(".Id").html();
            if (Id == @IdRowSelect)
            {
                $(this).click();
                $(document).scrollTop($(this).position().top);
            }
        });
       $("#WebGrid th:nth-child(1),td:nth-child(1)").hide();
    });

    $("body").on("click", "#WebGrid tr", function () {
        $("#WebGrid").find("td").removeClass("selectedrow");
        $(this).find("td").addClass("selectedrow");
    });
</script>

WebReportMWM v40.0.0/WebReportMWM/Views/CrudDestinos/UpdateCreate.cshtml
@model WebReportMWM.Models.Entitys.Destino
@using WebReportMWM.services
@using WebReportMWM.HelperMethodsRepository;
@{
    ViewBag.Title = "create";

    bool modeCreate = (bool)ViewBag.ModeCreate;
    string textAction = modeCreate ? "Crear" : "Actualizar";
}

<h2>@textAction</h2>

@using (Html.BeginForm(modeCreate ? "Create" : "Update", "CrudDestinos", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Destino</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@textAction class="btn btn-danger" />
                @Html.ActionLink("Listar", "List", "CrudDestinos", new { @class = "btn btn-info" })
                @ViewBag.Message
            </div>
        </div>
    </div>
  
    if (TempData["MessagesError"] != null && ((List<string>)TempData["MessagesError"]).Count > 0)
    {
        foreach (string msg in (List<string>)TempData["MessagesError"])
        {
            <p style="color:red;">@msg</p>
        }
    }


}