WebReportMWM v40.0.0/WebReportMWM/Controllers/CrudEtiquetasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebReportMWM.Models;
using WebReportMWM.Models.Entitys;
using WebReportMWM.services;

namespace WebReportMWM.Controllers
{
    [Authorize(Roles = "S")]
    public class CrudEtiquetasController : Controller
    {
        // GET: CrudEtiquetas

        public ActionResult Create()
        {
            using (var context = new DMMeatWeigherModel())
            {
                Etiqueta model = new Etiqueta();
                ViewBag.ModeCreate = true;
                return View("UpdateCreate", model);
            }
        }

        [HttpPost]
        public ActionResult Create(Etiqueta model)
        {
            using (var context = new DMMeatWeigherModel())
            {
                Etiqueta newEtiqueta = new Etiqueta();
                newEtiqueta.Nombre = model.Nombre;
                newEtiqueta.Descripcion = model.Descripcion;
                newEtiqueta.IdTipoBulto = model.IdTipoBulto;

                ResultValidate resultValidation = DbServices.ValidateUpdateCreate_Etiqueta(newEtiqueta);
                if (resultValidation.Validated)
                {
                    context.Etiquetas.Add(newEtiqueta);
                    context.SaveChanges();
                    return RedirectToAction("List", new { idRowSelect = newEtiqueta.Id });
                }
                else
                {
                    TempData["MessagesError"] = resultValidation.ErrorMessages;
                    ViewBag.ModeCreate = true;
                    return View("UpdateCreate", newEtiqueta);
                }
            }
        }

        [HttpGet]
        public ActionResult List(int? idRowSelect)
        {
            if (idRowSelect == null)
                idRowSelect = 0;

            using (var context = new DMMeatWeigherModel())
            {
                var data = (from e in context.Etiquetas
                            join tb in context.TiposBulto
                            on e.IdTipoBulto equals tb.Id
                            select new
                            {
                                Id = e.Id,
                                Nombre = e.Nombre,
                                Descripcion = e.Descripcion,
                                IdTipoBulto = e.IdTipoBulto,
                                TipoBulto = tb.Nombre
                            }).AsEnumerable().Select(x => new Etiqueta()
                            {
                                Id = x.Id,
                                Nombre = x.Nombre,
                                Descripcion = x.Descripcion,
                                IdTipoBulto = x.IdTipoBulto,
                                TipoBulto    = x.TipoBulto
                            }).ToList();
                ViewBag.IdRowSelect = idRowSelect;
                return View(data);
            }
        }

        public ActionResult Update(int idEtiqueta)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var date = context.Etiquetas.Where(x => x.Id == idEtiqueta).SingleOrDefault();
                Etiqueta model = new Etiqueta()
                {
                    Id = date.Id,
                    Nombre = date.Nombre,
                    Descripcion = date.Descripcion,
                    IdTipoBulto = date.IdTipoBulto
                };
                ViewBag.ModeCreate = false;
                return View("UpdateCreate", model);
            }
        }

        [HttpPost]
        public ActionResult Update(Etiqueta model)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var data = context.Etiquetas.FirstOrDefault(x => x.Id == model.Id);
                if (data != null)
                {
                    data.Nombre = model.Nombre;
                    data.Descripcion = model.Descripcion;
                    data.IdTipoBulto = model.IdTipoBulto;
                }

                ResultValidate resultValidation = DbServices.ValidateUpdateCreate_Etiqueta(model);
                if (resultValidation.Validated)
                {
                    context.SaveChanges();
                    return RedirectToAction("List", new { idRowSelect = data.Id });
                }
                else
                {
                    TempData["MessagesError"] = resultValidation.ErrorMessages;
                    ViewBag.ModeCreate = false;
                    return View("UpdateCreate", data);
                }
            }
        }

        public ActionResult ConfirmDelete(int idEtiqueta)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var data = context.Etiquetas.FirstOrDefault(x => x.Id == idEtiqueta);
                return View(data);
            }
        }

        [HttpPost]
        public ActionResult Delete(int idEtiqueta)
        {
            using (var context = new DMMeatWeigherModel())
            {
                var data = context.Etiquetas.FirstOrDefault(x => x.Id == idEtiqueta);
                if (data != null)
                {
                    var resultValidation = DbServices.ValidateDelete_Etiqueta(data.Id);
                    if (resultValidation.Validated)
                    {
                        context.Etiquetas.Remove(data);
                        context.SaveChanges();
                        return RedirectToAction("List");
                    }
                    else
                    {
                        TempData["MessagesError"] = resultValidation.ErrorMessages;
                        return View("ConfirmDelete", data);
                    }
                }
                else
                {
                    ViewBag.Message = "En base de datos: No se ha podido eliminar el Operador.";
                    return View("Error");
                }
            }
        }
    }
}

WebReportMWM v40.0.0/WebReportMWM/Views/CrudEtiquetas/ConfirmDelete.cshtml
@model WebReportMWM.Models.Entitys.Etiqueta
@{
    ViewBag.Title = "Delete";
}

<h2>Borrar</h2>
<hr />
<h3>Confirma Eliminar esta Etiqueta?</h3>

@using (Html.BeginForm("Delete", "CrudEtiquetas", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <input type="hidden" id="idEtiqueta" name="idEtiqueta" value="@Model.Id" />

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control", disabled = "disabled", @readonly = "readonly", style = "max-width:60%;" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Borrar" class="btn btn-danger" />
                @Html.ActionLink("Listar", "List", "CrudEtiquetas", new { @class = "btn btn-info" })
            </div>
        </div>
    </div>

    if (TempData["MessagesError"] != null && ((List<string>)TempData["MessagesError"]).Count > 0)
    {
        foreach (string msg in (List<string>)TempData["MessagesError"])
        {
            <p style="color:red;">@msg</p>
        }
    }
}

WebReportMWM v40.0.0/WebReportMWM/Views/CrudEtiquetas/List.cshtml
@model IEnumerable<WebReportMWM.Models.Entitys.Etiqueta>
@{
    ViewBag.Title = "List";
}

@{ WebGrid webGrid = new WebGrid(source: Model, canPage: false, canSort: false);

    string IdRowSelect = ViewBag.IdRowSelect == null ? "0" : ((int)ViewBag.IdRowSelect).ToString();

}

<h2>Lista de Etiquetas</h2>

<p>
    <a href="~/CrudEtiquetas/Create" class="btn btn-default btn-sm">
        <i class="glyphicon glyphicon-star" style="color: aqua;"></i>
        <span>
            <strong>Crear Nuevo</strong>
        </span>
    </a>
</p>

@webGrid.GetHtml(htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
            tableStyle: "table table-bordered",
            rowStyle: "webgrid-row",
            fillEmptyRows: false,
            alternatingRowStyle: "alt",
            headerStyle: "webgrid-header",
            columns: webGrid.Columns(
            webGrid.Column(columnName: "Id", header: "Id", style: "Id"),
            webGrid.Column(columnName: "Nombre", header: "Nombre", style: "colnombre"),
            webGrid.Column(columnName: "Descripcion", header: "Descripción", style: "colnombre"),
            webGrid.Column(columnName: "TipoBulto", header: "Tipo Bulto", style: "coltipo"),
            webGrid.Column(header: "", style: "collinks", format:@<span class="link">
                @Html.ActionLink(" ", "Update", new { idEtiqueta = item.Id }, new { @class = "glyphicon glyphicon-edit", title = "Editar" }) |
                @Html.ActionLink(" ", "ConfirmDelete", new { idEtiqueta = item.Id }, new { @style = "color:#ff0000;", @class = "glyphicon glyphicon-trash", title = "Eliminar" })
            </span>)))

<style type="text/css">
    .webgrid-header th {
        padding: 6px 5px;
        text-align: center;
        background-color: #e8eef4;
        border-bottom: 2px solid #3966A2;
        height: 40px;
        font-weight: bold;
        border-top: 2px solid #D6E8FF;
        border-left: 2px solid #D6E8FF;
        border-right: 2px solid #D6E8FF;
    }

    .alt {
        background-color: #FBFBFB;
        color: #000;
    }

    .label {
        color: #000;
        font-weight: normal;
    }

    .selectedrow {
        background-color: gold;
    }

    .collinks {
        width: 8%;
        text-align: center;
    }

    .coltipo {
        width: 15%;
        text-align: center;
    }

    .colnombre {
        justify-content: left;
    }
</style>

<script type="text/javascript" src="~/Scripts/jquery-3.4.1.min.js"></script>

<script type="text/javascript">
    //Al iniciar la carga del documento selecciono el registro especificado por su valor de Id
    //Tambien pongo al registro visible controlando el scroll.
    $(document).ready(function () {
        $('#WebGrid tr').each(function () {
            var Id = $(this).find(".Id").html();
            if (Id == @IdRowSelect)
            {
                $(this).click();
                $(document).scrollTop($(this).position().top);
            }
        });

        $("#WebGrid th:nth-child(1),td:nth-child(1)").hide();

    });

    $("body").on("click", "#WebGrid tr", function () {
        $("#WebGrid").find("td").removeClass("selectedrow");
        $(this).find("td").addClass("selectedrow");
    });
</script>

WebReportMWM v40.0.0/WebReportMWM/Views/CrudEtiquetas/UpdateCreate.cshtml
@model WebReportMWM.Models.Entitys.Etiqueta
@using WebReportMWM.services
@{
    ViewBag.Title = "create";

    var ListTipoBultos = DbServices.GetBultosToListSelectListItem();

    bool modeCreate = (bool)ViewBag.ModeCreate;
    string textAction = modeCreate ? "Crear" : "Actualizar";
}

<h2>@textAction</h2>

@using (Html.BeginForm(modeCreate ? "Create" : "Update", "CrudEtiquetas", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Etiqueta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", style = "max-width:60%;" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoBulto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdTipoBulto, ListTipoBultos, new { htmlAttributes = new { @class = "form-control", style = "Width:50%", id = "iddropdownlistTipoBultos" } })
                @Html.ValidationMessageFor(model => model.IdTipoBulto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@textAction class="btn btn-danger" />
                @Html.ActionLink("Listar", "List", "CrudEtiquetas", new { @class = "btn btn-info" })
                @ViewBag.Message
            </div>
        </div>
    </div>
    if (TempData["MessagesError"] != null && ((List<string>)TempData["MessagesError"]).Count > 0)
    {
        foreach (string msg in (List<string>)TempData["MessagesError"])
        {
            <p style="color:red;">@msg</p>
        }
    }
}

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        /*Esta funcion captura el evento de cambio del dropdownlist para asignar el nuevo id
                 seleccionado al idTipo del modelo. Esto se debe hacer por jquery porque si no el
                 modelo no se actualiza cuando se realiza una seleccion del dropdownlist*/
        $(document).ready(function () {
            $('#iddropdownlistTipoBultos').change(function () {
                $('#idTipoBulto').val($('#iddropdownlistTipoBultos option:selected').val());
            });
        });
    </script>

}